[tool.ruff]
target-version = "py311"
line-length = 100
select = ["E", "F", "I"]
exclude = [".git", "__pycache__", "venv", ".venv"]
src = ["app", "tests"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["app"]
